name: Django CI with Coverage

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set secret key
        env:
          DJANGO_SECRET_KEY: 'test-secret-key-for-ci'
        run: echo "Using secret key for CI"

      - name: Run tests
        env:
          DJANGO_SECRET_KEY: 'test-secret-key-for-ci'
        run: |
          poetry run python manage.py test