name: Django CI with Coverage

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: "True"
      DJANGO_SECRET_KEY: "test-secret-key"
      CSRF_TRUSTED_ORIGINS: "http://localhost,http://127.0.0.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run python manage.py test